### ISSUE TITLE
afterActions doesn’t trigger?

### ISSUE THREAD

**Issue by tomsoderlund** [ryo718/mongoose-crudify#1]
Thank you for a great NPM package!

I defined `afterActions` such as:

	afterActions: [
		{ middlewares: [stripIds] },
	],

But they don't trigger. Moving them up to `beforeActions` works.

What I want to achieve is formatting the final JSON results.

**Comment by ryo718** [comment]
Hi Tom,
My first thought is you need to include a next() call in main action. I have updated the readme and included a working version of using before/after actions. Hope this helps:)

**Comment by tomsoderlund** [comment]
Thank you! However, I'm using only the default `actions`:

	const logProperties = function (req, res, next) {
		console.log('logProperties:');
		// Get types for all properties for the arguments object
		let result = {};
		for (let key in arguments) {
			result[key] = typeof(arguments[key]);
		}
		console.log(result);
		next();
	};

	module.exports = function (app, config, authController) {

		app.use(
			'/api/users',
			mongooseCrudify({
				Model: User,
				identifyingKey: 'externalId',
				afterActions: [
					{ middlewares: [logProperties] },
				],
			})
		);

	};

**Question:** if I want to modify the resulting JSON from e.g. the `create` action, would I need to override the `actions.create` function then?

**Comment by ryo718** [comment]
Hi Tom,
Yes you'll have to override the [default create action](https://github.com/ryo718/mongoose-crudify/blob/master/index.js#L131)

**Comment by tomsoderlund** [comment]
OK thanks!

Any other ideas why `afterActions` doesn’t trigger?

**Comment by ryo718** [comment]
Hi Tom,
Still it's because the next() call is not there in the default actions, so it should be all good if you include a next call in your create action. 
 If you want to call logProperties after each lcrud, for now you will have to override them all...

**Comment by tomsoderlund** [comment]
Cool, I understand now.

Is this behavior intended/by design? I _love_ the simple plug-in approach to `beforeActions`/`afterActions`. But having to override `actions` just to trigger `afterActions` seems unnecessary. Plus, I find that in 90% of my API cases I need to modify the resulting JSON in some way - having a similar “plug-in” approach to that would be great.

I can help out, just want to hear your thoughts.

**Comment by ryo718** [comment]
Well, I'm amateur:) so any suggestion or contribution is welcomed.
I have done a bit change in 0.2.0 branch:

1. now default actions will call next() if action has after action defined.
2. query result stored in req.crudify.result.
3. specifying option endResponseInAction to be false will delay sending response in default actions, so you can modify it and res.send it in after actions

**Comment by tomsoderlund** [comment]
Wow will check it out!

Did you build these features just now? Or were you planning them earlier on?

**Comment by tomsoderlund** [comment]
Hi Ryo, your code works great, thank you!

**Comment by ryo718** [comment]
Hi Tom, thanks for the feedback! published on npm too
