### ISSUE TITLE
No error when Mongoose validation fails

### ISSUE THREAD

**Issue by tomsoderlund** [ryo718/mongoose-crudify#2]
Hi @ryo718, hope all is well!

I just added your awesome mongoose-crudify to [**nextjs-express-mongoose-crudify-boilerplate**](https://github.com/tomsoderlund/nextjs-express-mongoose-crudify-boilerplate), and realised I got no errors (HTTP code 200) when Mongoose validations failed (e.g. missing a `required` field).

Is this intentional? Could the `strict` option be relevant here – I couldn't find any documentation on it:

	options: {
		// https://expressjs.com/en/api.html#express.router
		// if no existing router passed in, new one will be created with these options
		// all default to false
		caseSensitive: false,
		mergeParams: false,
		strict: false
	}

**Comment by ryo718** [comment]
Hi tom,
Currently most of the default actions are returning whatever result as a JSON, so you will need to do validation against that JSON content
