### ISSUE TITLE
Correct usage of loadModel:false?

### ISSUE THREAD

**Issue by tomsoderlund** [ryo718/mongoose-crudify#3]
Hi!

From the README:

	// load model on update and read actions, defaults to true
	// store the found model instance in req, eg: req.crudify.article
	// if changed to false, you must override the update and read middlewares

So if I want a custom find/get method, what's the best way to implement?

My guess:

	// Allow both /api/lessons/slug=tyrannosaurus-rex and /api/lessons/5a3921c358bb5d65332ab9f1
	const findLessonFromSlugOrId = function (req, res, next) {
		const paramsArray = _.get(req, 'params._id', '').split('=');
		const query = paramsArray[0] === 'slug' ? { slug: paramsArray[1] } : { _id: paramsArray[paramsArray.length - 1] };
		Lesson.findOne(query).exec((err, result) => {
			req.crudify = {err, result};
			next();
		})
	};

	module.exports = function (server, router) {

		server.use(
			'/api/lessons',
			mongooseCrudify({
				Model: Lesson,
				loadModel: false,
				beforeActions: [
					{ middlewares: [findLessonFromSlugOrId], only: ['read', 'update'] },
				]
			})
		);

	};

...but this doesn’t return any results, i.e. it seems like my `next()` doesn’t trigger the _action_ afterwards.

**Comment by tomsoderlund** [comment]
Ah, I think I also need to set this property:

	req.crudify.lesson = result;

**Comment by ryo718** [comment]
Hi Tom,
yes, you are right, is the code working alright then?

**Comment by tomsoderlund** [comment]
Yes, now works fine
