### ISSUE TITLE
list action could use filter in query

### ISSUE THREAD

**Issue by avowkind** [ryo718/mongoose-crudify#6]
Would it be possible for the list action to take a query parameter for the mongodb filter and fetch just the matching documents?

e.g /api/articles?filter='{ status: "draft" } .  fetches all the draft articles. 

I can override the list action with a custom version

If can filter then also project fields, collate and sort results by passing most of the query params onto db.

**Comment by prateekm03** [comment]
Can I get some help, looking for similar functionality?

**Comment by avowkind** [comment]
Hi @prateekm03 you can see my current solution here: https://github.com/voluntarily/vly2/blob/master/server/api/person/person.controller.js

However, having to override the crudify default list hander does make it less useful. Its rare in real world solutions where you would want to fetch all elements in a collection without some selection.

**Comment by prateekm03** [comment]
Thanks, I already found the solution to it.
